services:
  importer:
    image: ghcr.io/yohancourbe/firefly-ponto-importer:latest
    restart: always
    environment:
      - FIREFLY_API_URL=xx
      - FIREFLY_ACCESS_TOKEN=xx
      - PONTO_CLIENT_ID=xx
      - PONTO_CLIENT_SECRET=xx